#!/usr/bin/python3

import yaml
import argparse

# https://stackoverflow.com/questions/25108581/python-yaml-dump-bad-indentation


class MyDumper(yaml.Dumper):
    def increase_indent(self, flow=False, indentless=False):
        return super(MyDumper, self).increase_indent(flow, False)


def add(schema, configure):
    if schema in configure['schema_list']:
        print('Schema ' + schema['schema'] + ' already exist in default.yaml')
        return
    configure['schema_list'].append(schema)


def remove(schema, configure):
    if schema not in configure['schema_list']:
        print('Schema ' + schema['schema'] + ' doesn‘t exist in default.yaml')
        return
    configure['schema_list'].remove(schema)

def set_default_schema(schema, configure):
    with open('/etc/rime-default-schema.conf', 'w') as f:
        f.write(schema)

def main():
    parser = argparse.ArgumentParser(description='rime-schema-manage is a tool to manage /usr/share/rime-data/default.yaml')
    parser.add_argument('--set-default-schema', help="Set default schema. eg: rime-schema-manager --set-default-schema luna_pinyin")
    parser.add_argument('--add', help="Add schema to schema list. eg: rime-schema-manager --add luna_pinyin", nargs='+')
    parser.add_argument('--remove', help="Remove schema in schema list. eg: rime-schema-manager --remove luna_pinyin", nargs='+')
    args = parser.parse_args()

    with open('/usr/share/rime-data/default.yaml', 'r') as f:
        configure = yaml.safe_load(f)

    with open('/etc/rime-default-schema.conf', 'r') as f:
        default = f.readline()

    if type(configure['schema_list']) == list:
        configure['schema_list'] = configure.get('schema_list', [])
    else:
        configure['schema_list'] = []

    if args.add:
        schemas = args.add
        for schema in schemas:
            schema = {'schema': schema}
            add(schema, configure)

    if args.remove:
        schemas = args.remove
        for schema in schemas:
            schema = {'schema': schema}
            remove(schema, configure)

    if args.set_default_schema:
        schema = args.set_default_schema
        set_default_schema(schema, configure)

    configure['schema'].remove({'schema': default})
    configure['schema'].insert(0, {'schema': default})

    with open('/usr/share/rime-data/default.yaml', 'w') as f:
        yaml.dump(configure, Dumper=MyDumper,
                  default_flow_style=False, stream=f)


if __name__ == '__main__':
    main()
